name: productcatalogue
description: Product Catalogue App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+30
# chan on 12/6/2022 LV:13
environment:
  sdk: ">=2.17.0 <3.0.0"

module:
  androidX: true

dependencies:
  advance_pdf_viewer2: ^2.0.4
  badges: ^3.1.1
  bot_toast: ^4.0.3
  cloud_firestore: ^4.5.2
  collection: ^1.17.0
  connectivity: ^3.0.6
  csv: ^5.0.1
  cupertino_icons: ^1.0.5
  external_path: ^1.0.3
  file_picker: ^4.6.1
  firebase_analytics: ^10.2.1
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_downloader: ^1.10.2
  flutter_email_sender: ^5.2.0
  flutter_secure_storage: ^8.0.0
  flutter_typeahead: ^4.3.7
  getwidget: ^3.0.1
  google_mobile_ads: ^2.4.0
  google_sign_in: ^6.1.0
  googleapis_auth: ^1.4.0
  grouped_checkbox: ^1.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_cropper: ^3.0.2
  image_picker: ^0.8.7+3
  open_file: ^3.2.1
  path_provider: ^2.0.14
  pdf: ^3.10.1
  permission_handler: ^10.2.0
  provider: ^6.0.5
  rate_my_app: ^1.1.3
  upi_india: ^3.0.1
  url_launcher: ^6.1.10
  wc_flutter_share: ^0.4.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/Open_Sans/
    # - assets/google_logo.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
